//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopSimulator2015 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaptopSimulator2015.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string _continue {
            get {
                return ResourceManager.GetString("continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCDEFGHIJKLMNPQRSTUVWXYZ123456789.
        /// </summary>
        internal static string captchaLetters {
            get {
                return ResourceManager.GetString("captchaLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled Exception occured and the Application was terminated. Please contact the developer..
        /// </summary>
        internal static string consoleError {
            get {
                return ResourceManager.GetString("consoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any Key to quit..
        /// </summary>
        internal static string consolePress {
            get {
                return ResourceManager.GetString("consolePress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E X I T E D ..
        /// </summary>
        internal static string consoleQuit {
            get {
                return ResourceManager.GetString("consoleQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S T A R T I N G . . ..
        /// </summary>
        internal static string consoleStarting {
            get {
                return ResourceManager.GetString("consoleStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fake Desktop.
        /// </summary>
        internal static string fakeDesktopTitle {
            get {
                return ResourceManager.GetString("fakeDesktopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: We recommend you restart your game to apply these changes. Restart?.
        /// </summary>
        internal static string langWarning {
            get {
                return ResourceManager.GetString("langWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string lvPref {
            get {
                return ResourceManager.GetString("lvPref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSD Mode.
        /// </summary>
        internal static string optionsWindowLSD {
            get {
                return ResourceManager.GetString("optionsWindowLSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you SURE?\r\n(This will break EVERYTHING!).
        /// </summary>
        internal static string optionsWindowLSDWarning {
            get {
                return ResourceManager.GetString("optionsWindowLSDWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string optionsWindowTitle {
            get {
                return ResourceManager.GetString("optionsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedodated Wam.
        /// </summary>
        internal static string optionsWindowWam {
            get {
                return ResourceManager.GetString("optionsWindowWam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To verify that you are human we ask you to fill in this Captcha. This will only take a second..
        /// </summary>
        internal static string ramInstallerWindowText2 {
            get {
                return ResourceManager.GetString("ramInstallerWindowText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the installation to finish....
        /// </summary>
        internal static string ramInstallerWindowText3 {
            get {
                return ResourceManager.GetString("ramInstallerWindowText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset you progress?.
        /// </summary>
        internal static string resetWarning1 {
            get {
                return ResourceManager.GetString("resetWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you absolutly sure you want to reset you progress? This is your last chance to turn back!.
        /// </summary>
        internal static string resetWarning2 {
            get {
                return ResourceManager.GetString("resetWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string winMenuExit1 {
            get {
                return ResourceManager.GetString("winMenuExit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string winMenuExit2 {
            get {
                return ResourceManager.GetString("winMenuExit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string winMenuStart {
            get {
                return ResourceManager.GetString("winMenuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello and welcome to my game, I hope you&apos;ll like it. My name is CreepyCrafter24, btw. (FunFact: This game was originally created as the result of a conversation with a classmate).
        /// </summary>
        internal static string winMenuText {
            get {
                return ResourceManager.GetString("winMenuText", resourceCulture);
            }
        }
    }
}
